security:
    encoders:
        InteractiveValley\BackendBundle\Entity\Usuario:  { algorithm: sha512, iterations: 10 }

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_API:         ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        usuarios:
            entity: { class: InteractiveValley\BackendBundle\Entity\Usuario, property: email }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        secured_area:
            pattern: ^/backend
            provider: usuarios
            form_login:
                login_path: backend_login
                check_path: backend_login_check
                default_target_path: backend_homepage
                remember_me: true
                use_referer: true
            logout:
                path: backend_logout
                target: backend_login
            security: true
            anonymous: true

    access_control:
        - { path: ^/backend/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/backend/recuperar, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/backend, roles: [ ROLE_ADMIN ] }
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }