# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    richpolis.emails.to_email: rafael@interactivevalley.com
    richpolis.uploads: %kernel.root_dir%/../web/uploads

services:
    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }
